spring.application.name=dispatch-system

spring.profiles.active=local
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


app.cors.allowed-origin-patterns=http://localhost:*
