package com.ambulance.dispatch_system.triage.controller;

import com.ambulance.dispatch_system.triage.model.dto.TriageRequestDTO;
import com.ambulance.dispatch_system.triage.model.dto.TriageResponseDTO;
import com.ambulance.dispatch_system.triage.service.TriageService;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.*;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * REST controller responsible for handling triage-related requests.
 * Provides endpoints for evaluating patients, viewing the active queue,
 * and resolving completed triage cases.
 */
@RestController
@RequestMapping("/api/v1/triage")
public class TriageController {

    private final TriageService triageService;

    public TriageController(TriageService triageService) {
        this.triageService = triageService;
    }

    /**
     * Evaluates a new triage request and adds it to the triage queue.
     *
     * @param request patient triage information
     * @return generated triage response
     */
    @PostMapping("/evaluate")
    public ResponseEntity<TriageResponseDTO> evaluate(
            @Valid @RequestBody TriageRequestDTO request) {

        TriageResponseDTO response = triageService.evaluate(request);

        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    /**
     * Retrieves all currently active triage cases.
     *
     * @return list of active triage cases
     */
    @GetMapping("/queue")
    public ResponseEntity<List<TriageResponseDTO>> getQueue() {
        List<TriageResponseDTO> queue = triageService.getActiveQueue();

        return ResponseEntity.ok(queue);
    }

    /**
     * Marks a triage case as resolved.
     *
     * @param id unique identifier of the triage case
     * @return empty response with HTTP 204 status
     */
    @PutMapping("/{id}/resolve")
    public ResponseEntity<Void> markResolved(@PathVariable UUID id) {
        triageService.markResolved(id);

        return ResponseEntity.noContent().build();
    }

    /**
     * Handles validation errors generated by @Valid request objects.
     * Returns validation messages using the corresponding field names.
     *
     * @param ex validation exception
     * @return map containing field names and validation error messages
     */
    @ExceptionHandler(MethodArgumentNotValidException.class)
    @ResponseStatus(HttpStatus.BAD_REQUEST)
    public Map<String, String> handleValidationExceptions(
            MethodArgumentNotValidException ex) {

        Map<String, String> errors = new HashMap<>();

        ex.getBindingResult().getAllErrors().forEach((error) -> {
            String fieldName = ((FieldError) error).getField();
            String errorMessage = error.getDefaultMessage();

            errors.put(fieldName, errorMessage);
        });

        return errors;
    }
}